
  // const myError = new Error('luizar');

  // describe('Testando erros', () => {

  //   before(() => {
  //     sinon.stub(productModel, 'getAll').rejects(myError);
  //   });

  //   after(() => {
  //     productModel.getAll.restore();
  //   });

  //   it('All Errors', async () => {
  //     const err = await productModel.getAll();

  //     expect(err).equal(myError)

  //     console.log(err);
  //   });
  // });